/* Generated by Yosys 0.58 (git sha1 157aabb5831cc77d08346001c4a085f188d7c736, clang++ 17.0.0 -fPIC -O3) */

module assert_simple(clk, rst, data_in, data_out, overflow_flag);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [3:0] data_in;
  wire [3:0] data_in;
  output [3:0] data_out;
  reg [3:0] data_out;
  output overflow_flag;
  reg overflow_flag;
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  reg [3:0] counter;
  wire no_overflow_condition;
  assign _00_ = counter + 1'h1;
  always @(posedge clk)
    if (rst) data_out <= 4'h0;
    else data_out <= data_in;
  always @(posedge clk)
    if (rst) overflow_flag <= 1'h0;
    else if (_03_) overflow_flag <= 1'h1;
  always @(posedge clk)
    if (rst) counter <= 4'h0;
    else counter <= _00_;
  assign _01_ = data_in == 4'hf;
  assign _02_ = counter > 4'ha;
  assign _03_ = _01_ && _02_;
  assign _04_ = ! _03_;
  assign no_overflow_condition = rst || _04_;
  always @(posedge clk) begin
    if (1'h1) begin
      assert (no_overflow_condition);
    end
  end
endmodule
